DELETE { ?s ?p ?o } WHERE {
  VALUES ?s { %values% }
  # Since values are shared we can only clear the values on them when they are no longer used
  # anywhere else.
  FILTER NOT EXISTS { ?someEntity ?someStatementPred ?s .  }
  ?s ?p ?o .
};
