# Clear out of date site links
DELETE {
  ?s ?p ?o .
}
WHERE {
  ?s %schema:about% %entity:id% .
  ?s ?p ?o .
  # This construct is constantly reused throughout the updates.  Its job is to not delete statements
  # that are still in use.
  FILTER NOT EXISTS {
    VALUES ( ?s ?p ?o ) {
      %valueStatements%
    }
  }
};
# Clear out of date statements about statements
DELETE {
  ?s ?p ?o .
}
WHERE {
  %entity:id% ?statementPred ?s .
  FILTER( STRSTARTS(STR(?s), "%uris.statement%") ) .
  ?s ?p ?o .
  FILTER NOT EXISTS {
    VALUES ( ?s ?p ?o ) {
      %valueStatements%
    }
  }
};
# Clear out of date statements about the entity
DELETE {
  %entity:id% ?p ?o .
}
WHERE {
  %entity:id% ?p ?o .
  FILTER NOT EXISTS {
    VALUES ( ?s ?p ?o ) {
      %valueStatements%
    }
  }
};
INSERT {
  %insertStatements%
} WHERE {}

